hotbar:
  7:
    material: BOOK
    amount: 1
    enchantments: false
    menu: "cmd:help"
    name: "&eHelp"
    lore:
      - "Welcome! "
  8:
    material: DIAMOND
    amount: 1
    enchantments:
      - "unbreaking:2"
    hide-enchantments: true
    menu: test
    name: "&eMenu"
    lore:
      - "Welcome! "
